# Generated by Django 5.0.6 on 2024-05-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Code', models.CharField(max_length=200)),
                ('Flag_URL', models.CharField(max_length=200)),
            ],
        ),
    ]
