# Generated by Django 5.0.6 on 2024-05-12 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_season'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='Flag_URL',
            new_name='Image_URL',
        ),
        migrations.RenameField(
            model_name='league',
            old_name='Logo_URL',
            new_name='Image_URL',
        ),
        migrations.AddField(
            model_name='league',
            name='Country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.country'),
        ),
        migrations.AddField(
            model_name='season',
            name='League',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.league'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Code', models.CharField(max_length=200)),
                ('Image_URL', models.CharField(max_length=200)),
                ('Country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.country')),
                ('League', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.league')),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=200)),
                ('Image_URL', models.CharField(max_length=200)),
                ('Country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.country')),
                ('Team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.team')),
            ],
        ),
    ]
