# Generated by Django 5.0.6 on 2024-05-12 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_player_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='Nationality',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
