# Generated by Django 5.0.6 on 2024-05-12 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_flag_url_country_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_Stats_Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Form', models.CharField(max_length=200)),
                ('Played', models.IntegerField()),
                ('Wins', models.IntegerField()),
                ('Draws', models.IntegerField()),
                ('Losses', models.IntegerField()),
                ('Goals_For_Home', models.IntegerField()),
                ('Goals_For_Home_Avg', models.IntegerField()),
                ('Goals_For_Away', models.IntegerField()),
                ('Goals_For_Away_Avg', models.IntegerField()),
                ('Clean_sheets', models.IntegerField()),
            ],
        ),
    ]
