# Generated by Django 5.0.6 on 2024-05-12 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_team_stats_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_stats_season',
            name='Season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.season'),
        ),
        migrations.AddField(
            model_name='team_stats_season',
            name='Team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.team'),
        ),
    ]
