# Generated by Django 5.0.6 on 2024-05-12 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_team_stats_season_season_team_stats_season_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_stats_season',
            name='GoalDiff',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team_stats_season',
            name='Points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team_stats_season',
            name='Rank',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Referee', models.CharField(max_length=200)),
                ('TeamH', models.IntegerField()),
                ('TeamA', models.IntegerField()),
                ('League', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.league')),
                ('Stadium', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.stadium')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=200)),
                ('Lastname', models.CharField(max_length=200)),
                ('Height', models.CharField(max_length=200)),
                ('Weight', models.CharField(max_length=200)),
                ('Injured', models.BooleanField()),
                ('Image_URL', models.CharField(max_length=200)),
                ('Nationality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.country')),
            ],
        ),
    ]
