# Generated by Django 5.0.6 on 2024-05-12 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_team_stats_season_goaldiff_team_stats_season_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='Team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.team'),
        ),
    ]
