# Generated by Django 5.0.6 on 2024-05-12 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_player_nationality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Multiplier', models.IntegerField()),
                ('Bookmarker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.bookmarker')),
            ],
        ),
    ]
