# Generated by Django 5.0.6 on 2024-05-14 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_bet_fixture_bet_value_bet_api_id_bookmarker_api_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='Country',
            field=models.CharField(default='Country', max_length=200),
            preserve_default=False,
        ),
    ]
