# Generated by Django 5.0.6 on 2024-05-14 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_team_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='League',
        ),
    ]
