# Generated by Django 5.0.6 on 2024-05-16 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timballapp', '0002_remove_competiciones_idapipais_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competiciones',
            old_name='Pais',
            new_name='IdApiPais',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='Pais',
            new_name='IdApiPais',
        ),
    ]
