# Generated by Django 5.0.6 on 2024-05-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timballapp', '0003_rename_pais_competiciones_idapipais_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='IdApiPais',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
