# Generated by Django 5.0.6 on 2024-05-16 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timballapp', '0004_pais_idapipais'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competiciones',
            old_name='IdApiPais',
            new_name='Pais',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='IdApiPais',
            new_name='Pais',
        ),
        migrations.RemoveField(
            model_name='pais',
            name='IdApiPais',
        ),
    ]
