# Generated by Django 5.0.6 on 2024-05-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timballapp', '0006_remove_competiciones_temporada'),
    ]

    operations = [
        migrations.AddField(
            model_name='competiciones',
            name='Temporada',
            field=models.IntegerField(default=2024),
            preserve_default=False,
        ),
    ]
