# Generated by Django 5.0.4 on 2024-05-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timballapp', '0007_competiciones_temporada'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='Numero',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
