# Generated by Django 5.0.6 on 2024-05-17 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timballapp', '0008_jugador_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apuesta',
            name='Porcentaje',
        ),
    ]
