# Generated by Django 5.0.6 on 2024-05-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timballapp', '0009_remove_apuesta_porcentaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apuesta',
            name='Multiplicador',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
