# Generated by Django 5.0.6 on 2024-05-17 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timballapp', '0010_alter_apuesta_multiplicador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tecnico',
            name='Altura',
        ),
        migrations.RemoveField(
            model_name='tecnico',
            name='Peso',
        ),
    ]
