# Generated by Django 5.0.6 on 2024-05-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timballapp', '0011_remove_tecnico_altura_remove_tecnico_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='IdApiComp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
