# Generated by Django 5.0.6 on 2024-05-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timballapp', '0012_fixture_idapicomp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmaker',
            name='id',
        ),
        migrations.RemoveField(
            model_name='competiciones',
            name='id',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='estadio',
            name='id',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='id',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tecnico',
            name='id',
        ),
        migrations.AlterField(
            model_name='bookmaker',
            name='Bookmaker',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='competiciones',
            name='IdApiComp',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='IdApiEquipo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='estadio',
            name='IdApiEstadio',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='IdApiFixture',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='IdApiJugador',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='IdApiTecnico',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
