# Generated by Django 5.0.6 on 2024-05-17 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timballapp', '0013_remove_bookmaker_id_remove_competiciones_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competiciones',
            old_name='IdApiComp',
            new_name='IdApiComp_id',
        ),
        migrations.AlterField(
            model_name='equipo',
            name='IdApiComp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timballapp.competiciones'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='IdApiComp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timballapp.competiciones'),
        ),
    ]
