# Generated by Django 5.0.6 on 2024-05-17 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timballapp', '0014_rename_idapicomp_competiciones_idapicomp_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='IdApiEstadio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Local', to='timballapp.equipo'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='IdEquipoLocal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Visitante', to='timballapp.equipo'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='IdApiEquipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timballapp.equipo'),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='IdApiEquipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timballapp.equipo'),
        ),
    ]
