# Generated by Django 5.0.6 on 2024-05-17 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timballapp', '0015_alter_fixture_idapiestadio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmaker',
            old_name='Bookmaker',
            new_name='Bookmaker_id',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='IdApiEquipo',
            new_name='IdApiEquipo_id',
        ),
        migrations.RenameField(
            model_name='estadio',
            old_name='IdApiEstadio',
            new_name='IdApiEstadio_id',
        ),
        migrations.RenameField(
            model_name='fixture',
            old_name='IdApiFixture',
            new_name='IdApiFixture_id',
        ),
        migrations.RenameField(
            model_name='jugador',
            old_name='IdApiJugador',
            new_name='IdApiJugador_id',
        ),
        migrations.RenameField(
            model_name='tecnico',
            old_name='IdApiTecnico',
            new_name='IdApiTecnico_id',
        ),
        migrations.AlterField(
            model_name='fixture',
            name='IdApiEstadio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timballapp.estadio'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='IdEquipoLocal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Local', to='timballapp.equipo'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='IdEquipoVisitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Visitante', to='timballapp.equipo'),
        ),
    ]
