# Generated by Django 5.0.6 on 2024-05-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timballapp', '0016_rename_bookmaker_bookmaker_bookmaker_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiApuestas',
            fields=[
                ('IdApiApuesta', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=200)),
            ],
        ),
    ]
