# Generated by Django 5.0.6 on 2024-05-21 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timballapp', '0017_apiapuestas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apuesta_P',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdApiFixture', models.IntegerField()),
                ('IdApiBookmaker', models.IntegerField()),
                ('IdApiApuesta', models.IntegerField()),
                ('Nombre', models.CharField(max_length=200)),
                ('Tipo', models.CharField(max_length=200)),
                ('Porcentaje', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='apuesta',
            name='Nombre',
        ),
    ]
