# Generated by Django 5.0.6 on 2024-05-21 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timballapp', '0018_apuesta_p_remove_apuesta_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apuesta',
            name='IdApiApuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timballapp.apiapuestas'),
        ),
    ]
