# Generated by Django 5.0.6 on 2024-05-21 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timballapp', '0019_alter_apuesta_idapiapuesta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apuesta_p',
            name='Nombre',
        ),
        migrations.RemoveField(
            model_name='apuesta_p',
            name='Tipo',
        ),
        migrations.AlterField(
            model_name='apuesta',
            name='IdApiBookmaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timballapp.bookmaker'),
        ),
        migrations.AlterField(
            model_name='apuesta',
            name='IdApiFixture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timballapp.equipo'),
        ),
        migrations.AlterField(
            model_name='apuesta_p',
            name='IdApiApuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timballapp.apiapuestas'),
        ),
    ]
