# Generated by Django 5.0.6 on 2024-05-21 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timballapp', '0020_remove_apuesta_p_nombre_remove_apuesta_p_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apuesta',
            name='IdApiFixture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timballapp.fixture'),
        ),
    ]
