# Generated by Django 5.0.6 on 2024-05-22 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timballapp', '0021_alter_apuesta_idapifixture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apuesta_p',
            name='IdApiBookmaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timballapp.bookmaker'),
        ),
        migrations.AlterField(
            model_name='apuesta_p',
            name='IdApiFixture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timballapp.fixture'),
        ),
    ]
