# Generated by Django 5.0.6 on 2024-05-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timballapp', '0023_apuesta_p_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apuesta_p',
            name='Porcentaje',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
