# Generated by Django 5.0.6 on 2024-05-22 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timballapp', '0026_alter_apuesta_idapifixture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apuesta',
            name='IdApiFixture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timballapp.fixture'),
        ),
    ]
