# Generated by Django 5.0.6 on 2024-06-04 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timballapp', '0027_alter_apuesta_idapifixture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='IdApiEstadio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timballapp.estadio'),
        ),
    ]
