# Generated by Django 5.0.6 on 2024-06-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timballapp', '0028_alter_equipo_idapiestadio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiapuestas',
            name='Nombre',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='apuesta',
            name='Multiplicador',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='apuesta',
            name='Porcentaje',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='apuesta',
            name='Tipo',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='bookmaker',
            name='Nombre',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='competiciones',
            name='Image_URL',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='competiciones',
            name='Nombre',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='competiciones',
            name='Pais',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='competiciones',
            name='Temporada',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='Fundacion',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='Image_URL',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='Nombre',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='Pais',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='estadio',
            name='Capacidad',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='estadio',
            name='Ciudad',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='estadio',
            name='Direccion',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='estadio',
            name='Image_URL',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='estadio',
            name='Nombre',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='Arbitro',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='Fecha',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='Hora',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='Status',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='Altura',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='Edad',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='Image_URL',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='Nacionalidad',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='Nombre',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='Numero',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='Peso',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='Posicion',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='pais',
            name='Image_URL',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='pais',
            name='Nombre',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='Edad',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='Image_URL',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='Nacionalidad',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='Nombre',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
