# Generated by Django 5.0.6 on 2024-06-07 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timballapp', '0031_alter_apiapuestas_nombre_alter_apuesta_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='Altura',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='Edad',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='Image_URL',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='Nacionalidad',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='Nombre',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='Numero',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='Peso',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='Posicion',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
