# Generated by Django 5.0.6 on 2024-06-07 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timballapp', '0033_delete_jugador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('IdApiJugador_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=200, null=True)),
                ('Edad', models.IntegerField(null=True)),
                ('Image_URL', models.CharField(max_length=200, null=True)),
                ('Posicion', models.CharField(max_length=200, null=True)),
                ('Numero', models.IntegerField(null=True)),
                ('IdApiEquipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timballapp.equipo')),
            ],
        ),
    ]
