# Generated by Django 5.0.6 on 2024-06-07 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timballapp', '0035_jugador_altura_jugador_nacionalidad_jugador_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='Altura',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jugador',
            name='Edad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jugador',
            name='Image_URL',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jugador',
            name='Nacionalidad',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jugador',
            name='Nombre',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jugador',
            name='Numero',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jugador',
            name='Peso',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jugador',
            name='Posicion',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
