# Generated by Django 5.0.6 on 2024-06-23 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timballapp', '0036_alter_jugador_altura_alter_jugador_edad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='Altura',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='Nacionalidad',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='Peso',
        ),
    ]
