# Generated by Django 5.0.6 on 2024-07-10 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timballapp', '0037_remove_jugador_altura_remove_jugador_nacionalidad_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pais',
        ),
    ]
