# Generated by Django 5.0.4 on 2024-08-19 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timballapp', '0038_delete_pais'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsEquipo',
            fields=[
                ('IdApiEquipo_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='StatsJugador',
            fields=[
                ('IdApiJugador_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Goles', models.IntegerField()),
                ('PorcentajePases', models.IntegerField()),
                ('PorcentajePasesF', models.IntegerField()),
                ('FaltasRecibidas', models.IntegerField()),
                ('FaltasDadas', models.IntegerField()),
                ('Asistencias', models.IntegerField()),
                ('Amarillas', models.IntegerField()),
                ('Rojas', models.IntegerField()),
                ('PasesClave', models.IntegerField()),
                ('Tiros', models.IntegerField()),
                ('Quites', models.IntegerField()),
                ('Minutos', models.IntegerField()),
                ('PartidosJugados', models.IntegerField()),
                ('Atajadas', models.IntegerField()),
                ('PromedioGoles', models.IntegerField()),
            ],
        ),
    ]
