# Generated by Django 5.0.4 on 2024-10-01 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timballapp', '0042_alter_statsequipo_idapiequipo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statsequipo',
            name='Penales',
        ),
    ]
