# Generated by Django 5.0.4 on 2024-10-01 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timballapp', '0043_remove_statsequipo_penales'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatsEquipo',
        ),
    ]
