# Generated by Django 5.0.4 on 2024-10-01 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timballapp', '0044_delete_statsequipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsEquipo',
            fields=[
                ('IdApiEquipo_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='timballapp.equipo')),
                ('GolesFavor', models.IntegerField(default=0)),
                ('GolesContra', models.IntegerField(default=0)),
                ('DiferenciaGoles', models.IntegerField(default=None, null=True)),
                ('PartidosJugados', models.IntegerField(default=0)),
                ('PartidosGanados', models.IntegerField(default=0)),
                ('PartidosPerdidos', models.IntegerField(default=0)),
                ('PartidosEmpatados', models.IntegerField(default=0)),
                ('Puntos', models.IntegerField(default=None, null=True)),
                ('PuntosLocal', models.IntegerField(default=None, null=True)),
                ('PuntosVisitante', models.IntegerField(default=None, null=True)),
                ('PartidosGanadosLocal', models.IntegerField(default=0)),
                ('PartidosPerdidosLocal', models.IntegerField(default=0)),
                ('PartidosEmpatadosLocal', models.IntegerField(default=0)),
                ('PartidosGanadosVisitante', models.IntegerField(default=0)),
                ('PartidosEmpatadosVisitante', models.IntegerField(default=0)),
                ('PartidosPerdidosVisitante', models.IntegerField(default=0)),
                ('GolesFavorLocal', models.IntegerField(default=0)),
                ('GolesFavorVisitante', models.IntegerField(default=0)),
                ('SinGoles', models.IntegerField(default=0)),
                ('SinGolesLocal', models.IntegerField(default=0)),
                ('SinGolesVisitante', models.IntegerField(default=0)),
                ('Amarillas', models.IntegerField(default=None, null=True)),
                ('Rojas', models.IntegerField(default=None, null=True)),
                ('GolesContraLocal', models.IntegerField(default=0)),
                ('GolesContraVisitante', models.IntegerField(default=0)),
            ],
        ),
    ]
