# Generated by Django 5.0.4 on 2024-10-01 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timballapp', '0045_statsequipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='statsequipo',
            name='Penales',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statsequipo',
            name='PenalesErrados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statsequipo',
            name='PenalesMetidos',
            field=models.IntegerField(default=0),
        ),
    ]
