# Generated by Django 5.0.4 on 2024-10-08 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timballapp', '0046_statsequipo_penales_statsequipo_penaleserrados_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jugador',
        ),
    ]
