# Generated by Django 5.0.4 on 2024-10-08 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timballapp', '0048_jugador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='Edad',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='IdApiEquipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timballapp.equipo'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='Image_URL',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='Nombre',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='Numero',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='Posicion',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
