# Generated by Django 5.0.4 on 2024-10-08 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timballapp', '0049_alter_jugador_edad_alter_jugador_idapiequipo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jugador',
        ),
    ]
