# Generated by Django 5.0.4 on 2024-10-08 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timballapp', '0050_delete_jugador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('IdApiJugador_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=200, null=True)),
                ('Edad', models.IntegerField(null=True)),
                ('Image_URL', models.CharField(max_length=200, null=True)),
                ('Posicion', models.CharField(max_length=200, null=True)),
                ('Numero', models.IntegerField(null=True)),
                ('IdApiEquipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timballapp.equipo')),
            ],
        ),
    ]
